wip

diff --git a/patch/13x/auto13 b/patch/13x/auto13
--- a/patch/13x/auto13
+++ b/patch/13x/auto13
@@ -26,7 +26,9 @@
 # SUCH DAMAGE.
 #
 # $FreeBSD$
-#
+# CBSD
+BSDINSTALL_DISTSITE="http://myb.convectix.com"
+export BSDINSTALL_DISTSITE
 ############################################################ INCLUDES
 
 BSDCFG_SHARE="/usr/share/bsdconfig"
@@ -49,7 +51,7 @@ msg_auto_zfs="Auto (ZFS)"
 msg_auto_zfs_desc="Guided Root-on-ZFS"
 msg_auto_zfs_help="To use ZFS with less than 8GB RAM, see https://wiki.freebsd.org/ZFSTuningGuide"
 msg_exit="Exit"
-msg_freebsd_installer="$OSNAME Installer"
+msg_freebsd_installer="MyBee Installer"
 msg_gpt_active_fix="Your hardware is known to have issues booting in CSM/Legacy/BIOS mode from GPT partitions that are not set active. Would you like the installer to apply this workaround for you?"
 msg_lenovo_fix="Your model of Lenovo is known to have a BIOS bug that prevents it booting from GPT partitions without UEFI. Would you like the installer to apply a workaround for you?"
 msg_manual="Manual"
@@ -77,6 +79,7 @@ error()
 	local prompt="${1:+$1\n\n}$msg_an_installation_step_has_been_aborted"
 	local hline="$hline_arrows_tab_space_enter"
 
+	[ "$DISTDIR_IS_UNIONFS" ] && umount -f "$BSDINSTALL_DISTDIR"
 	[ -f "$PATH_FSTAB" ] && bsdinstall umount
 
 	local height width
@@ -143,53 +146,55 @@ dialog_workaround()
 
 f_dprintf "Began Installation at %s" "$( date )"
 
+BSDINSTALL_TMPETC=/tmp/etc
 rm -rf $BSDINSTALL_TMPETC
 mkdir $BSDINSTALL_TMPETC
 
-[ -f /usr/libexec/bsdinstall/local.pre-everything ] && f_dprintf "Running local.pre-everything" && sh /usr/libexec/bsdinstall/local.pre-everything "$BSDINSTALL_CHROOT"
-
 trap true SIGINT	# This section is optional
-[ -z "$BSDINSTALL_SKIP_KEYMAP" ] && bsdinstall keymap
+#bsdinstall keymap
 
 trap error SIGINT	# Catch cntrl-C here
-if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall hostname || error "Set hostname failed"; fi
+bsdinstall hostname || error "Set hostname failed"
 
-export DISTRIBUTIONS="${DISTRIBUTIONS:-base.txz kernel.txz}"
-if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
-	DISTMENU=`awk -F'\t' '!/^(kernel\.txz|base\.txz)/{print $1,$5,$6}' $BSDINSTALL_DISTDIR/MANIFEST`
-	DISTMENU="$(echo ${DISTMENU} | sed -E 's/\.txz//g')"
+# CBSD
+#export DISTRIBUTIONS="base.txz kernel.txz"
+export DISTRIBUTIONS="base.txz cbsd.txz kernel.txz"
+#if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
+#	DISTMENU=`awk -F'\t' '!/^(kernel\.txz|base\.txz)/{print $1,$5,$6}' $BSDINSTALL_DISTDIR/MANIFEST`
+#	DISTMENU="$(echo ${DISTMENU} | sed -E 's/\.txz//g')"
+#
+#	exec 3>&1
+#	EXTRA_DISTS=$( eval dialog \
+#	    --backtitle \"MyBee Installer\" \
+#	    --title \"Distribution Select\" --nocancel --separate-output \
+#	    --checklist \"Choose optional system components to install:\" \
+#	    0 0 0 $DISTMENU \
+#	2>&1 1>&3 )
+#	for dist in $EXTRA_DISTS; do
+#		export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
+#	done
+#fi
 
-	if [ -n "$DISTMENU" ]; then
-		exec 3>&1
-		EXTRA_DISTS=$( eval dialog \
-		    --backtitle \"$OSNAME Installer\" \
-		    --title \"Distribution Select\" --nocancel --separate-output \
-		    --checklist \"Choose optional system components to install:\" \
-		    0 0 0 $DISTMENU \
-		2>&1 1>&3 )
-		for dist in $EXTRA_DISTS; do
-			export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
-		done
-	fi
-fi
-
+#LOCAL_DISTRIBUTIONS="MANIFEST"
 FETCH_DISTRIBUTIONS=""
 for dist in $DISTRIBUTIONS; do
 	if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
 		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
+	else
+		LOCAL_DISTRIBUTIONS="$LOCAL_DISTRIBUTIONS $dist"
 	fi
 done
+LOCAL_DISTRIBUTIONS=`echo $LOCAL_DISTRIBUTIONS`	# Trim white space
+FETCH_DISTRIBUTIONS=`echo $FETCH_DISTRIBUTIONS`	# Trim white space
 
 if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
-	dialog --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
+	dialog --backtitle "MyBee Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
 	bsdinstall netconfig || error
 	NETCONFIG_DONE=yes
 fi
 
 rm -f $PATH_FSTAB
 touch $PATH_FSTAB
-
-[ -f /usr/libexec/bsdinstall/local.pre-partition ] && f_dprintf "Running local.pre-partition" && sh /usr/libexec/bsdinstall/local.pre-partition "$BSDINSTALL_CHROOT"
 
 #
 # Try to detect known broken platforms and apply their workarounds
@@ -284,26 +289,32 @@ if f_interactive; then
 	esac
 fi
 
-PMODES="
-	'$msg_auto_ufs' '$msg_auto_ufs_desc' '$msg_auto_ufs_help'
+# CBSD
+#PMODES="
+#	'$msg_auto_ufs' '$msg_auto_ufs_desc' '$msg_auto_ufs_help'
+#	'$msg_manual' '$msg_manual_desc' '$msg_manual_help'
+#	'$msg_shell' '$msg_shell_desc' '$msg_shell_help'
+#" # END-QUOTE
+PMODES="\
+	'$msg_auto_zfs' '$msg_auto_zfs_desc' '$msg_auto_zfs_help'
 	'$msg_manual' '$msg_manual_desc' '$msg_manual_help'
 	'$msg_shell' '$msg_shell_desc' '$msg_shell_help'
 " # END-QUOTE
 
 CURARCH=$( uname -m )
-case $CURARCH in
-	amd64|arm64|i386|riscv)	# Booting ZFS Supported
-		PMODES="
-			'$msg_auto_zfs' '$msg_auto_zfs_desc' '$msg_auto_zfs_help'
-			$PMODES
-		" # END-QUOTE
-		;;
-	*)			# Booting ZFS Unsupported
-		;;
-esac
+#case $CURARCH in
+#	amd64|arm64|i386|riscv)	# Booting ZFS Supported
+#		PMODES="
+#			'$msg_auto_zfs' '$msg_auto_zfs_desc' '$msg_auto_zfs_help'
+#			$PMODES
+#		" # END-QUOTE
+#		;;
+#	*)			# Booting ZFS Unsupported
+#		;;
+#esac
 
 exec 3>&1
-PARTMODE=`echo $PMODES | xargs dialog --backtitle "$OSNAME Installer" \
+PARTMODE=`echo $PMODES | xargs dialog --backtitle "MyBee Installer" \
 	--title "Partitioning" \
 	--item-help \
 	--menu "How would you like to partition your disk?" \
@@ -338,23 +349,89 @@ case "$PARTMODE" in
 	;;
 esac
 
-[ -f /usr/libexec/bsdinstall/local.pre-fetch ] && f_dprintf "Running local.pre-fetch" && sh /usr/libexec/bsdinstall/local.pre-fetch "$BSDINSTALL_CHROOT"
+if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
+	ALL_DISTRIBUTIONS="$DISTRIBUTIONS"
+	WANT_DEBUG=
 
-if [ -n "$FETCH_DISTRIBUTIONS" ]; then
-	exec 3>&1
-	export BSDINSTALL_DISTDIR=$(`dirname $0`/fetchmissingdists 2>&1 1>&3)
-	FETCH_RESULT=$?
-	exec 3>&-
+	# Download to a directory in the new system as scratch space
+	BSDINSTALL_FETCHDEST="$BSDINSTALL_CHROOT/usr/freebsd-dist"
+	mkdir -p "$BSDINSTALL_FETCHDEST" || error "Could not create directory $BSDINSTALL_FETCHDEST"
 
-	[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
+	export DISTRIBUTIONS="$FETCH_DISTRIBUTIONS"
+	# Try to use any existing distfiles
+	#if [ -d $BSDINSTALL_DISTDIR ]; then
+	if [ -n "${BSDINSTALL_DISTDIR}" -a -d $BSDINSTALL_DISTDIR ]; then
+		DISTDIR_IS_UNIONFS=1
+		mount_nullfs -o union "$BSDINSTALL_FETCHDEST" "$BSDINSTALL_DISTDIR"
+	else
+		export DISTRIBUTIONS="$FETCH_DISTRIBUTIONS"
+		export BSDINSTALL_DISTDIR="$BSDINSTALL_FETCHDEST"
+	fi
+
+	export FTP_PASSIVE_MODE=YES
+	# Iterate through the distribution list and set a flag if debugging
+	# distributions have been selected.
+	for _DISTRIBUTION in $DISTRIBUTIONS; do
+		case $_DISTRIBUTION in
+			*-dbg.*)
+				[ -e $BSDINSTALL_DISTDIR/$_DISTRIBUTION ] \
+					&& continue
+				WANT_DEBUG=1
+				DEBUG_LIST="\n$DEBUG_LIST\n$_DISTRIBUTION"
+				;;
+			*)
+				;;
+		esac
+	done
+
+	# CBSD
+	[ ! -r ${BSDINSTALL_DISTDIR}/MANIFEST ] && fetch -o ${BSDINSTALL_DISTDIR}/MANIFEST ${BSDINSTALL_DISTSITE}/MANIFEST
+
+	# Fetch the distributions.
+	bsdinstall distfetch
+	rc=$?
+
+	if [ $rc -ne 0 ]; then
+		# If unable to fetch the remote distributions, recommend
+		# deselecting the debugging distributions, and retrying the
+		# installation, since failure to fetch *-dbg.txz should not
+		# be considered a fatal installation error.
+		msg="Failed to fetch remote distribution"
+		if [ ! -z "$WANT_DEBUG" ]; then
+			# Trim leading and trailing newlines.
+			DEBUG_LIST="${DEBUG_LIST%%\n}"
+			DEBUG_LIST="${DEBUG_LIST##\n}"
+			msg="$msg\n\nPlease deselect the following distributions"
+			msg="$msg and retry the installation:"
+			msg="$msg\n$DEBUG_LIST"
+		fi
+		error "$msg"
+	fi
+	export DISTRIBUTIONS="$ALL_DISTRIBUTIONS"
 fi
+
+if [ ! -z "$LOCAL_DISTRIBUTIONS" ]; then
+	# Download to a directory in the new system as scratch space
+	BSDINSTALL_FETCHDEST="$BSDINSTALL_CHROOT/usr/freebsd-dist"
+	mkdir -p "$BSDINSTALL_FETCHDEST" || error "Could not create directory $BSDINSTALL_FETCHDEST"
+	# Try to use any existing distfiles
+	#if [ -d $BSDINSTALL_DISTDIR ]; then
+	if [ -n "${BSDINSTALL_DISTDIR}" -a -d $BSDINSTALL_DISTDIR ]; then
+		DISTDIR_IS_UNIONFS=1
+		mount_nullfs -o union "$BSDINSTALL_FETCHDEST" "$BSDINSTALL_DISTDIR"
+		export BSDINSTALL_DISTDIR="$BSDINSTALL_FETCHDEST"
+	fi
+	env DISTRIBUTIONS="$LOCAL_DISTRIBUTIONS" \
+		BSDINSTALL_DISTSITE="file:///usr/freebsd-dist" \
+		bsdinstall distfetch || \
+		error "Failed to fetch distribution from local media"
+fi
+
 bsdinstall checksum || error "Distribution checksum failed"
 bsdinstall distextract || error "Distribution extract failed"
 
 # Set up boot loader
 bsdinstall bootconfig || error "Failed to configure bootloader"
-
-[ -f /usr/libexec/bsdinstall/local.pre-configure ] && f_dprintf "Running local.pre-configure" && sh /usr/libexec/bsdinstall/local.pre-configure "$BSDINSTALL_CHROOT"
 
 bsdinstall rootpass || error "Could not set root password"
 
@@ -362,20 +439,21 @@ trap true SIGINT	# This section is optional
 if [ "$NETCONFIG_DONE" != yes ]; then
 	bsdinstall netconfig	# Don't check for errors -- the user may cancel
 fi
-[ -z "$BSDINSTALL_SKIP_TIME" ] && bsdinstall time
-[ -z "$BSDINSTALL_SKIP_SERVICES" ] && bsdinstall services
-[ -z "$BSDINSTALL_SKIP_HARDENING" ] && bsdinstall hardening
 
-[ -z "$BSDINSTALL_SKIP_USERS" ] && dialog --backtitle "$OSNAME Installer" \
-	--title "Add User Accounts" --yesno \
+# CBSD
+bsdinstall time
+#bsdinstall services
+#bsdinstall hardening
+
+dialog --backtitle "MyBee Installer" --title "Add User Accounts" --yesno \
     "Would you like to add users to the installed system now?" 0 0 && \
     bsdinstall adduser
 
 finalconfig() {
 	exec 3>&1
-	REVISIT=$(dialog --backtitle "$OSNAME Installer" \
+	REVISIT=$(dialog --backtitle "MyBee Installer" \
 	    --title "Final Configuration" --no-cancel --menu \
-	    "Setup of your $OSNAME system is nearly complete. You can now modify your configuration choices. After this screen, you will have an opportunity to make more complex changes using a shell." 0 0 0 \
+	    "Setup of your FreeBSD system is nearly complete. You can now modify your configuration choices. After this screen, you will have an opportunity to make more complex changes using a shell." 0 0 0 \
 		"Exit" "Apply configuration and exit installer" \
 		"Add User" "Add a user to the system" \
 		"Root Password" "Change root password" \
@@ -384,7 +462,7 @@ finalconfig() {
 		"Services" "Set daemons to run on startup" \
 		"System Hardening" "Set security options" \
 		"Time Zone" "Set system timezone" \
-		"Handbook" "Install $OSNAME Handbook (requires network)" 2>&1 1>&3)
+		"Handbook" "Install FreeBSD Handbook (requires network)" 2>&1 1>&3)
 	exec 3>&-
 
 	case "$REVISIT" in
@@ -423,28 +501,112 @@ finalconfig() {
 	esac
 }
 
+#CBSD
+# pkg chroot install ?
+[ -z "${BSDINSTALL_CHROOT}" ] && BSDINSTALL_CHROOT=/mnt
+echo "=== MyBee post-install ==="
+echo
+
+# devfs already mounted here
+chroot ${BSDINSTALL_CHROOT} /bin/sh <<XEOF
+
+sysrc -qf /boot/loader.conf module_path="/boot/kernel;/boot/modules;/boot/dtb;/boot/dtb/overlays"
+
+truncate -s0 /etc/motd /etc/motd.template /var/run/motd
+set -o xtrace
+
+sysrc -qf /etc/rc.conf \
+ nginx_enable="YES" \
+ clear_tmp_enable="YES" \
+ beanstalkd_enable="YES" \
+ beanstalkd_flags="-l 127.0.0.1 -p 11300" \
+ kld_list="if_bridge vmm if_tap nmdm if_vether" \
+ ntpdate_enable="YES" \
+ ntpd_enable="YES" \
+ ntpd_sync_on_start="YES" \
+ cbsd_mq_api_enable="YES" \
+ cbsd_mq_router_enable="YES" \
+ sshd_enable="YES" \
+ sshd_flags="-oUseDNS=no -oPermitRootLogin=without-password -oPort=22" \
+ syslogd_enable="NO" \
+ sendmail_enable="NO" \
+ sendmail_submit_enable="NO" \
+ sendmail_outbound_enable="NO" \
+ sendmail_msp_queue_enable="NO" > /dev/null 2>&1
+# MyBee
+
+#clear
+
+cd /cbsd
+# FIND
+tar xfz pkg.pkg
+
+env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes /cbsd/usr/local/sbin/pkg-static add -f /cbsd/pkg.pkg || true
+
+hash -r
+
+env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes /usr/sbin/pkg add -f /cbsd/*.pkg || true
+
+hash -r
+
+/usr/local/bin/rsync -avz /usr/local/myb/jail-skel/ /
+[ ! -d /root/bin ] && mkdir -p /root/bin
+/usr/local/bin/rsync -avz /usr/local/myb/myb-extras/bin/ /root/bin/ || true
+
+echo "rsync done"
+
+cat > /etc/rc.initial <<EOF
+/usr/bin/tail -f /var/log/mybinit.log
+EOF
+
+touch /var/log/mybinit.log
+
+[ ! -d /usr/local/etc/rc.d ] && mkdir -p /usr/local/etc/rc.d
+cat > /usr/local/etc/rc.d/mybinst.sh <<EOF
+export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
+/usr/sbin/daemon -o /var/log/mybinit.log /bin/sh /usr/local/myb/mybinst.sh
+EOF
+chmod +x /usr/local/etc/rc.d/mybinst.sh
+#CBSD
+
+ls -la /usr/local/etc/rc.d/
+cat /etc/rc.initial
+
+XEOF
+
 # Allow user to change his mind
-[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && finalconfig
+finalconfig
 
 trap error SIGINT	# SIGINT is bad again
 bsdinstall config  || error "Failed to save config"
+
+if [ -n "$DISTDIR_IS_UNIONFS" ]; then
+	umount -f $BSDINSTALL_DISTDIR
+fi
 
 if [ ! -z "$BSDINSTALL_FETCHDEST" ]; then
 	rm -rf "$BSDINSTALL_FETCHDEST"
 fi
 
-[ -f /usr/libexec/bsdinstall/local.post-configure ] && f_dprintf "Running local.post-configure" && sh /usr/libexec/bsdinstall/local.post-configure "$BSDINSTALL_CHROOT"
+cat > ${BSDINSTALL_CHROOT}/boot/loader.conf <<EOF
+loader_menu_title="Welcome to MyBee Project"
+module_path="/boot/kernel;/boot/modules;/boot/dtb;/boot/dtb/overlays"
+cryptodev_load="YES"
+opensolaris_load="YES"
+zfs_load="YES"
+EOF
 
-if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
-	dialog --backtitle "$OSNAME Installer" --title "Manual Configuration" \
-		--default-button no --yesno \
-		"The installation is now finished. Before exiting the installer, would you like to open a shell in the new system to make any final manual modifications?" 0 0
-	if [ $? -eq 0 ]; then
-		clear
-		echo This shell is operating in a chroot in the new system. \
-		    When finished making configuration changes, type \"exit\".
-		chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
-	fi
+echo "CONFIG"
+cat ${BSDINSTALL_CHROOT}/boot/loader.conf
+
+dialog --backtitle "MyBee Installer" --title "Manual Configuration" \
+    --default-button no --yesno \
+   "The installation is now finished. Before exiting the installer, would you like to open a shell in the new system to make any final manual modifications?" 0 0
+if [ $? -eq 0 ]; then
+	clear
+	echo This shell is operating in a chroot in the new system. \
+	    When finished making configuration changes, type \"exit\".
+	chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
 fi
 
 bsdinstall entropy
